### ISSUE TITLE
main branch doesn't compile.  AstSmt & AstExpr size assertions.

### ISSUE THREAD

**Issue by hulto** [facebookexperimental/starlark-rust#54] opened 2022-09-11 16:15 UTC
Following the guide in the read me I ran into this error.
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/7121375/189537879-2a5517f3-535d-462b-bf23-f72c1c8aabe2.png">

Updating the size assertions fixes the problem and starlark-rust seems to work as intended.
<img width="710" alt="image" src="https://user-images.githubusercontent.com/7121375/189537943-4a00f887-23f8-4e0a-bf90-c47b88ea4da5.png">

Rust version:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/7121375/189538076-13553efa-7ef5-4694-8e24-2c22e23c5e03.png">

**Comment by sschnug** [comment] 2022-09-12 15:05
I observed this too and my hacky workaround (within some CI sys) looks like:

    RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly-2022-09-07-x86_64-unknown-linux-gnu -y

This works and might indicate, that the origin of the issue is relatively fresh.

**Comment by ndmitchell** [comment] 2022-09-15 20:51
Thanks for the report. The main branch is now failing CI. I guess this means that Rust nightly has improved the data density and probably reduced memory required for the AST, which is fantastic news. I'll go adjust the assertions (or comment them out til everyone has moved).

**Comment by ndmitchell** [comment] 2022-09-16 08:05
Should be all fixed now. Thanks for the ping. Turns out that AstLiteral embedded in AstExpr used to add 2 padding words, now only 1.

**Closed by ndmitchell** 2022-09-16 08:05 UTC
